GET http://127.0.0.1:8000/snippets/
Content-Type: application/json

###

POST http://127.0.0.1:8000/snippets/
Content-Type: application/json

{
  "title": "",
  "code": "newObject = NewObjectClass()",
  "linenos": false,
  "language": "python",
  "style": "friendly"
}

###
GET http://127.0.0.1:8000/snippets/1
Content-Type: application/json